# Generated by Django 5.0.7 on 2024-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='no description'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='in progress', max_length=20),
        ),
    ]
